//! Generator behaviour: determinism, operation shapes, errors, and `--check`.
#![allow(clippy::expect_used, clippy::float_cmp, clippy::too_many_lines)] // tests: expect with messages, exact asserts

use std::path::{Path, PathBuf};
use std::process::Command;

use pretty_assertions::assert_eq;
use serde_json::{Value, json};
use strata_codegen::{Error, Options, check, generate, write};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn committed_doc() -> Value {
    let text = std::fs::read_to_string(root().join("api/openapi.json")).expect("contract exists");
    serde_json::from_str(&text).expect("valid JSON")
}

fn options() -> Options {
    Options {
        rustfmt_config: Some(root().join("rustfmt.toml")),
        ..Options::default()
    }
}

/// A small contract exercising every parameter and body shape the template supports.
fn sample_doc() -> Value {
    let problem = json!({ "$ref": "#/components/responses/Problem" });
    json!({
        "openapi": "3.1.0",
        "security": [{ "bearer": [] }],
        "components": {
            "responses": { "Problem": { "description": "problem" } },
            "schemas": {
                "Item": {
                    "type": "object",
                    "required": ["id", "count", "kind"],
                    "properties": {
                        "id": { "type": "string", "format": "ulid" },
                        "count": { "type": "integer", "format": "int64", "minimum": 0 },
                        "kind": { "$ref": "#/components/schemas/Kind" },
                        "note": { "type": ["string", "null"] },
                    },
                },
                "Kind": { "type": "string", "enum": ["a", "b"] },
            },
        },
        "paths": {
            "/api/v1/items/{id}": {
                "put": {
                    "operationId": "put_item",
                    "summary": "Replace an item.",
                    "parameters": [
                        { "name": "id", "in": "path", "required": true, "schema": { "type": "string", "format": "ulid" } },
                        { "name": "If-Match", "in": "header", "required": true, "schema": { "type": "string" } },
                        { "name": "kind", "in": "query", "schema": { "$ref": "#/components/schemas/Kind" } },
                        { "name": "limit", "in": "query", "required": true, "schema": { "type": "integer", "minimum": 0 } },
                    ],
                    "requestBody": { "required": true, "content": { "application/vnd.msgpack": { "schema": { "$ref": "#/components/schemas/Item" } } } },
                    "responses": {
                        "200": { "description": "ok", "content": { "application/vnd.msgpack": { "schema": { "$ref": "#/components/schemas/Item" } } } },
                        "409": problem,
                    },
                },
                "delete": {
                    "operationId": "delete_item",
                    "security": [{}],
                    "parameters": [{ "name": "id", "in": "path", "required": true, "schema": { "type": "string" } }],
                    "responses": { "204": { "description": "gone" } },
                },
            },
        },
    })
}

fn file<'a>(files: &'a [strata_codegen::GeneratedFile], name: &str) -> &'a str {
    &files
        .iter()
        .find(|f| f.name == name)
        .expect("file generated")
        .contents
}

#[test]
fn generation_is_deterministic() {
    let a = generate(&committed_doc(), &options()).expect("generates");
    let b = generate(&committed_doc(), &options()).expect("generates");
    assert_eq!(a, b);
    let names: Vec<&str> = a.iter().map(|f| f.name).collect();
    assert_eq!(names, ["mod.rs", "operations.rs", "streams.rs", "types.rs"]);
    for f in &a {
        assert!(
            f.contents
                .starts_with("// @generated by strata-codegen from api/openapi.json."),
            "{}",
            f.name
        );
    }
}

#[test]
fn operations_follow_the_template() {
    let files = generate(&sample_doc(), &options()).expect("generates");
    let ops = file(&files, "operations.rs");
    let expected_put = r"/// Replace an item.
///
/// `PUT /api/v1/items/{id}`
pub async fn put_item(
    client: &crate::Client,
    id: ::ulid::Ulid,
    if_match: &str,
    kind: ::std::option::Option<&types::Kind>,
    limit: u64,
    body: &types::Item,
) -> ::std::result::Result<types::Item, crate::Error> {";
    assert!(ops.contains(expected_put), "{ops}");
    for fragment in [
        r#"request.header("If-Match", (*value).to_owned())"#,
        r#"request.query("kind", crate::param_string(value)?)"#,
        r#"request.query("limit", value.to_string())"#,
        "let request = request.authenticated();",
        "let request = request.body(body)?;",
        "client.send(request).await",
    ] {
        assert!(ops.contains(fragment), "missing `{fragment}` in\n{ops}");
    }
    // The public delete has no auth and an empty response.
    let delete = &ops[ops.find("pub async fn delete_item").expect("delete fn")..];
    let delete = &delete[..delete.find("\n}\n").expect("fn end")];
    assert!(delete.contains("-> ::std::result::Result<(), crate::Error>"));
    assert!(delete.contains("client.send_empty(request).await"));
    assert!(!delete.contains("authenticated"));

    let types = file(&files, "types.rs");
    for fragment in [
        "pub id: ::ulid::Ulid,",
        "pub count: u64,",
        "pub note: ::std::option::Option<::std::string::String>,",
        "#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]",
    ] {
        assert!(types.contains(fragment), "missing `{fragment}` in\n{types}");
    }
}

#[test]
fn unsupported_or_broken_documents_are_errors_not_panics() {
    let mut unresolved = sample_doc();
    unresolved["paths"]["/api/v1/items/{id}"]["put"]["requestBody"]["content"]["application/vnd.msgpack"]
        ["schema"] = json!({ "$ref": "#/components/schemas/Missing" });
    let mut json_body = sample_doc();
    let body = json_body["paths"]["/api/v1/items/{id}"]["put"]["requestBody"]["content"]
        .as_object_mut()
        .expect("content");
    let media = body.remove("application/vnd.msgpack").expect("media");
    body.insert("application/json".to_owned(), media);
    let mut duplicate = sample_doc();
    duplicate["paths"]["/api/v1/items/{id}"]["delete"]["operationId"] = json!("put_item");

    let cases = [
        (
            unresolved,
            "invalid OpenAPI document: unresolved $ref `#/components/schemas/Missing`",
        ),
        (
            json_body,
            "unsupported: PUT /api/v1/items/{id}: request media types [\"application/json\"]",
        ),
        (
            duplicate,
            "invalid OpenAPI document: duplicate operationId `put_item`",
        ),
    ];
    for (doc, message) in cases {
        let err = generate(&doc, &options()).expect_err("must fail");
        assert!(matches!(err, Error::Spec(_) | Error::Unsupported(_)));
        assert_eq!(err.to_string(), message);
    }
}

#[test]
fn check_reports_differences_missing_and_stale_files() {
    let dir = tempfile::tempdir().expect("temp dir");
    let files = generate(&sample_doc(), &options()).expect("generates");
    assert_eq!(
        check(dir.path(), &files).expect("checks"),
        [
            "mod.rs is missing",
            "operations.rs is missing",
            "streams.rs is missing",
            "types.rs is missing"
        ]
    );
    write(dir.path(), &files).expect("writes");
    assert_eq!(
        check(dir.path(), &files).expect("checks"),
        Vec::<String>::new()
    );
    std::fs::write(dir.path().join("types.rs"), "// edited\n").expect("edit");
    std::fs::write(dir.path().join("old.rs"), "").expect("stale");
    assert_eq!(
        check(dir.path(), &files).expect("checks"),
        ["old.rs should not exist", "types.rs differs"]
    );
    write(dir.path(), &files).expect("rewrites");
    assert!(!dir.path().join("old.rs").exists());
    assert_eq!(
        check(dir.path(), &files).expect("checks"),
        Vec::<String>::new()
    );
}

fn run_cli(args: &[&str]) -> (bool, String) {
    let out = Command::new(env!("CARGO_BIN_EXE_strata-codegen"))
        .args(args)
        .output()
        .expect("runs");
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

#[test]
fn cli_check_mode_exits_non_zero_when_stale() {
    let dir = tempfile::tempdir().expect("temp dir");
    let input = dir.path().join("openapi.json");
    std::fs::write(&input, sample_doc().to_string()).expect("input");
    let out = dir.path().join("generated");
    let (input, out_s) = (input.to_string_lossy(), out.to_string_lossy());

    let (ok, stderr) = run_cli(&["--input", &input, "--output", &out_s, "--check"]);
    assert!(!ok);
    assert!(stderr.contains("types.rs is missing"), "{stderr}");
    assert!(stderr.contains("generated client is stale: run api/generate.sh"));

    assert_eq!(
        run_cli(&["--input", &input, "--output", &out_s]),
        (true, String::new())
    );
    assert_eq!(
        run_cli(&["--input", &input, "--output", &out_s, "--check"]),
        (true, String::new())
    );

    std::fs::write(out.join("operations.rs"), "").expect("edit");
    let (ok, stderr) = run_cli(&["--input", &input, "--output", &out_s, "--check"]);
    assert!(!ok);
    assert!(stderr.contains("operations.rs differs"), "{stderr}");

    let (ok, stderr) = run_cli(&["--output", &out_s]);
    assert!(!ok);
    assert!(stderr.contains("--input is required"), "{stderr}");
}

#[test]
fn committed_client_matches_the_committed_contract() {
    let files = generate(&committed_doc(), &options()).expect("generates");
    let dir = root().join("api/rust-client/src/generated");
    assert_eq!(check(&dir, &files).expect("checks"), Vec::<String>::new());
}
