// The logic guard is a CLI: printing its report is its purpose.
// ignore_for_file: avoid_print

/// Enforces PLAN L15 ("Dart holds no logic") in the Flutter workspace:
///
/// 1. **Dependency allow-list.** Every workspace package may depend only on
///    the Flutter stack of PLAN §11.1 (plus a few packages allowed in one
///    specific package, e.g. `intl` for gen-l10n in `strata_l10n`). Anything
///    else fails, with a reason for well-known offenders (HTTP clients,
///    databases, key-value stores, file-system access).
/// 2. **Dart file locations.** Dart files may only live in `lib/`, `test/`
///    or `tool/` of a package (or be generated code).
///
/// Run with `dart run tool/logic_guard.dart [workspace-root]` (melos:
/// `melos run logic-guard`). Exits with 1 when a violation is found.
library;

import 'dart:io';

import 'package:meta/meta.dart';
import 'package:yaml/yaml.dart';

/// Runtime dependencies every UI package may use (PLAN §11.1).
const Map<String, String> allowedRuntime = {
  'flutter': 'Flutter SDK',
  'hooks_riverpod': 'Riverpod 3 (rebuilds and DI only)',
  'flutter_riverpod': 'Riverpod 3 (rebuilds and DI only)',
  'riverpod': 'Riverpod 3 (rebuilds and DI only)',
  'riverpod_annotation': 'riverpod_generator annotations',
  'flutter_hooks': 'ephemeral widget state',
};

/// Runtime dependencies allowed only in the named package.
const Map<String, Set<String>> scopedRuntime = {
  // App shell: routing, localisation delegates, notifications (D27).
  // `timezone` only types the instant handed to the plugin's
  // `zonedSchedule` (`TZDateTime`); no time maths in Dart (L15).
  // `file_selector`: the native save/open dialogs for export and import
  // paths (owner decision 2026-09-28); it returns a path, the core does the
  // rest.
  'strata': {
    'flutter_localizations',
    'go_router',
    'firebase_messaging',
    'flutter_local_notifications',
    'timezone',
    'file_selector',
  },
  // gen-l10n output needs intl and the SDK localisations.
  'strata_l10n': {'flutter_localizations', 'intl'},
  // flutter_rust_bridge v2 bindings (the only bridge to the Rust core).
  'strata_bridge': {'flutter_rust_bridge', 'ffi', 'path_provider'},
  // Rich-text editor (D2 = b).
  'strata_editor': {'super_editor', 'super_editor_markdown'},
  // `package:strata_state/testing.dart` (imported by tests only) holds the
  // shared §16.5 matrix and golden helpers, next to `flutter_test`.
  'strata_state': {'alchemist'},
};

/// Dev dependencies every package may use (tests, codegen, lints).
const Set<String> allowedDev = {
  'flutter_test',
  'integration_test',
  'patrol',
  'alchemist',
  'mocktail',
  'build_runner',
  'riverpod_generator',
  'go_router_builder',
  'riverpod_lint',
  'custom_lint',
  'very_good_analysis',
};

/// Dev dependencies allowed only in the named package: the app shell's icon
/// and native splash generators (run by hand; they write platform assets and
/// ship no Dart code).
const Map<String, Set<String>> scopedDev = {
  'strata': {'flutter_launcher_icons', 'flutter_native_splash'},
};

/// Dev dependencies of the workspace root (tooling only, no app code).
const Set<String> allowedWorkspaceTooling = {
  'melos',
  'meta',
  'test',
  'yaml',
  'very_good_analysis',
};

/// SDK packages that may be referenced with `sdk: flutter`.
const Set<String> allowedSdkPackages = {
  'flutter',
  'flutter_test',
  'flutter_localizations',
  'integration_test',
};

/// Why well-known packages are refused (the allow-list refuses everything
/// else too; these only get a clearer message).
const Map<String, String> knownViolations = {
  'http': 'networking belongs to the Rust core (L15)',
  'dio': 'networking belongs to the Rust core (L15)',
  'web_socket_channel': 'the event stream belongs to the Rust core (L15)',
  'connectivity_plus': 'connectivity is tracked by the Rust core (L15)',
  'sqflite': 'persistence belongs to the Rust core (L14, L15)',
  'sqlite3': 'persistence belongs to the Rust core (L14, L15)',
  'drift': 'persistence belongs to the Rust core (L14, L15)',
  'hive': 'persistence belongs to the Rust core (L14, L15)',
  'hive_flutter': 'persistence belongs to the Rust core (L14, L15)',
  'isar': 'persistence belongs to the Rust core (L14, L15)',
  'sembast': 'persistence belongs to the Rust core (L14, L15)',
  'shared_preferences': 'settings are stored by the Rust core (L15)',
  'flutter_secure_storage': 'tokens live in the local database (D14)',
  'path_provider': 'file-system access is only for strata_bridge (L15)',
  'file_selector': 'file dialogs belong to the app shell (FilePicker seam)',
  'json_serializable': 'no parsing in Dart (L15)',
  'freezed': 'view-model types are generated by frb (§11.1)',
};

/// Top-level package folders that may contain Dart files.
const Set<String> allowedDartFolders = {'lib', 'test', 'tool'};

/// A single guard failure.
@immutable
class Violation implements Comparable<Violation> {
  /// Creates a violation for [where] (package or file).
  const new(this.where, this.message);

  /// Package name or workspace-relative file path.
  final String where;

  /// What is wrong.
  final String message;

  @override
  int compareTo(Violation other) {
    final byWhere = where.compareTo(other.where);
    return byWhere != 0 ? byWhere : message.compareTo(other.message);
  }

  @override
  bool operator ==(Object other) =>
      other is Violation && other.where == where && other.message == message;

  @override
  int get hashCode => Object.hash(where, message);

  @override
  String toString() => '$where: $message';
}

/// A workspace member (or the workspace root itself).
class WorkspacePackage {
  /// Creates a package entry.
  const new({
    required this.name,
    required this.relativeDir,
    required this.pubspec,
  });

  /// Package name from its pubspec.
  final String name;

  /// Directory relative to the workspace root ('' for the root).
  final String relativeDir;

  /// Parsed pubspec.
  final YamlMap pubspec;

  /// Whether this is the workspace root.
  bool get isRoot => relativeDir.isEmpty;
}

/// Loads the workspace root and every member listed under `workspace:`
/// (entries may end in a `*` glob).
List<WorkspacePackage> loadWorkspace(Directory root) {
  final rootPubspec = _readPubspec(File('${root.path}/pubspec.yaml'));
  final packages = [
    WorkspacePackage(
      name: rootPubspec['name'] as String,
      relativeDir: '',
      pubspec: rootPubspec,
    ),
  ];
  final members = (rootPubspec['workspace'] as YamlList?) ?? YamlList();
  for (final entry in members.cast<String>()) {
    for (final dir in _expand(root, entry)) {
      final pubspec = _readPubspec(File('${root.path}/$dir/pubspec.yaml'));
      packages.add(
        WorkspacePackage(
          name: pubspec['name'] as String,
          relativeDir: dir,
          pubspec: pubspec,
        ),
      );
    }
  }
  return packages;
}

List<String> _expand(Directory root, String entry) {
  if (!entry.endsWith('/*')) return [entry];
  final parent = entry.substring(0, entry.length - 2);
  final dir = Directory('${root.path}/$parent');
  if (!dir.existsSync()) return const [];
  return [
    for (final child in dir.listSync().whereType<Directory>())
      if (File('${child.path}/pubspec.yaml').existsSync())
        '$parent/${child.uri.pathSegments.where((s) => s.isNotEmpty).last}',
  ]..sort();
}

YamlMap _readPubspec(File file) => loadYaml(file.readAsStringSync()) as YamlMap;

/// Checks one package's dependencies against the allow-list.
List<Violation> checkDependencies(
  WorkspacePackage package,
  Set<String> workspaceNames,
) {
  final violations = <Violation>[];
  void refuse(String dep, String section) {
    final reason = knownViolations[dep] ?? 'not in the §11.1 allow-list';
    violations.add(
      Violation(package.name, '$section "$dep" is not allowed: $reason'),
    );
  }

  void checkSection(String section, bool Function(String) allowed) {
    final deps = package.pubspec[section];
    if (deps == null) return;
    for (final entry in (deps as YamlMap).entries) {
      final dep = entry.key as String;
      final spec = entry.value;
      if (spec is YamlMap && spec.containsKey('sdk')) {
        if (!allowedSdkPackages.contains(dep)) {
          violations.add(
            Violation(package.name, '$section "$dep": unknown SDK package'),
          );
        }
        continue;
      }
      if (spec is YamlMap &&
          (spec.containsKey('path') || spec.containsKey('git'))) {
        violations.add(
          Violation(
            package.name,
            '$section "$dep": path/git dependencies are not allowed; '
            'use a workspace package or a hosted version',
          ),
        );
        continue;
      }
      if (workspaceNames.contains(dep)) continue;
      if (!allowed(dep)) refuse(dep, section);
    }
  }

  if (package.isRoot) {
    checkSection('dependencies', (_) => false);
    checkSection('dev_dependencies', allowedWorkspaceTooling.contains);
  } else {
    final scoped = scopedRuntime[package.name] ?? const <String>{};
    checkSection(
      'dependencies',
      (d) => allowedRuntime.containsKey(d) || scoped.contains(d),
    );
    final scopedDevDeps = scopedDev[package.name] ?? const <String>{};
    checkSection(
      'dev_dependencies',
      (d) => allowedDev.contains(d) || scopedDevDeps.contains(d),
    );
  }
  final overrides = package.pubspec['dependency_overrides'];
  if (overrides is YamlMap && overrides.isNotEmpty) {
    violations.add(
      Violation(package.name, 'dependency_overrides are not allowed'),
    );
  }
  return violations;
}

/// Directory names never scanned for Dart files (tool output, platform
/// build trees).
const Set<String> _skippedDirs = {'build', 'ephemeral', 'Pods'};

/// Whether [relativePath] (inside a package) is generated code.
bool isGenerated(String relativePath) =>
    relativePath.endsWith('.g.dart') ||
    relativePath.endsWith('.freezed.dart') ||
    relativePath.split('/').contains('generated');

/// Checks that every Dart file lives in an allowed folder of its package.
List<Violation> checkDartFiles(
  Directory root,
  List<WorkspacePackage> packages,
) {
  final memberDirs =
      packages.where((p) => !p.isRoot).map((p) => p.relativeDir).toList()
        ..sort((a, b) => b.length.compareTo(a.length));
  final violations = <Violation>[];
  final rootPath = root.path.replaceAll(r'\', '/');
  for (final file in _dartFiles(root)) {
    final path = file.path.replaceAll(r'\', '/').substring(rootPath.length + 1);
    final owner = memberDirs.firstWhere(
      (dir) => path.startsWith('$dir/'),
      orElse: () => '',
    );
    final inPackage = owner.isEmpty ? path : path.substring(owner.length + 1);
    final top = inPackage.split('/').first;
    final ok =
        inPackage.contains('/') &&
        (allowedDartFolders.contains(top) || isGenerated(inPackage));
    if (!ok) {
      violations.add(
        Violation(
          path,
          'Dart files must live in lib/, test/ or tool/ '
          '(L15: no logic outside the UI layers)',
        ),
      );
    }
  }
  return violations;
}

Iterable<File> _dartFiles(Directory dir) sync* {
  for (final entity in dir.listSync(followLinks: false)) {
    final name = entity.uri.pathSegments.where((s) => s.isNotEmpty).last;
    if (entity is Directory) {
      if (name.startsWith('.') || _skippedDirs.contains(name)) continue;
      yield* _dartFiles(entity);
    } else if (entity is File && name.endsWith('.dart')) {
      yield entity;
    }
  }
}

/// Runs every check and returns the sorted violations.
List<Violation> runGuard(Directory root) {
  final packages = loadWorkspace(root);
  final names = {for (final p in packages) p.name};
  return [
    for (final package in packages) ...checkDependencies(package, names),
    ...checkDartFiles(root, packages),
  ]..sort();
}

/// Entry point: `dart run tool/logic_guard.dart [workspace-root]`.
void main(List<String> args) {
  final root = Directory(args.isEmpty ? Directory.current.path : args.first)
      .absolute;
  final violations = runGuard(root);
  if (violations.isEmpty) {
    print('logic guard: OK (${loadWorkspace(root).length} packages checked)');
    return;
  }
  print('logic guard: ${violations.length} violation(s)');
  violations.map((v) => '  $v').forEach(print);
  exitCode = 1;
}
