targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          - lib/src/router/routes.dart
      riverpod_generator:
        generate_for:
          - lib/src/boot/core_bootstrap.dart
          - lib/src/router/router.dart
