//! # strata-core — the Strata client core (PLAN §12)
//!
//! All client logic lives here (L15); Flutter renders the view-models this crate streams and
//! forwards user intents. The layering is the hard rule of PLAN §12.1:
//!
//! | Layer | Role |
//! |---|---|
//! | [`api`] | the flutter_rust_bridge facade: the **only** surface Dart can call (async fns + streams) |
//! | [`view`] | view-model structs streamed to Dart, their builders and the watcher hub |
//! | [`store`] | one SQLite database per account (schema, migrations, FTS5), the write path and the outbox |
//! | [`sync`] | push / pull / bootstrap, conflicts, retry with backoff, connectivity |
//! | [`search`] | local full-text search over `text-normalize`d text |
//! | [`graph`] | local neighbourhoods from cached relations and links |
//! | [`auth`] | login, refresh, logout, token storage in the account database (D14), account states |
//! | [`format`] | `vault-format` adapters: parsing notes for the index and the editor |
//! | [`net`] | the generated `strata-client` and the transport traits the rest of the core uses |
//! | [`notify`] | the reminder notification plan (D27 = a, §12.5b) |
//!
//! Infrastructure shared by the layers: [`error`] (typed, localisation-ready errors),
//! [`clock`] and [`ids`] (injectable time and ULIDs), and [`session`] (the composition root that
//! wires one signed-in account's layers together).

// Tests assert exact values and may `expect` with a message stating the invariant.
#![cfg_attr(test, allow(clippy::expect_used, clippy::float_cmp))]

pub mod api;
pub mod auth;
pub mod clock;
pub mod error;
pub mod format;
pub mod graph;
pub mod ids;
pub mod net;
pub mod notify;
pub mod search;
pub mod session;
pub mod store;
pub mod sync;
pub mod view;

// Generated by flutter_rust_bridge_codegen (`client/app/packages/strata_bridge/flutter_rust_bridge.yaml`).
// The generated FFI entry points need `#[no_mangle]` (an unsafe attribute in edition 2024) and
// do not follow the workspace's pedantic lints.
#[allow(
    unsafe_code,
    missing_debug_implementations,
    clippy::all,
    clippy::pedantic,
    unused_qualifications,
    non_camel_case_types,
    non_snake_case,
    unreachable_patterns
)]
mod frb_generated;

pub use error::CoreError;
