//! Build-time prompt registry (PLAN §9.1: prompts live in `prompts/*.md` with versioned names).
//!
//! Every `prompts/<id>.v<N>.md` becomes one registry entry: its text is embedded with
//! `include_str!`, its SHA-256 is computed here, and `prompts/<id>.v<N>.schema.json` (if present)
//! is embedded as its output schema. The build fails if a prompt lacks the shared language
//! instruction (`prompts/_language.md`) verbatim, if a file name does not follow the scheme, or
//! if a schema file has no prompt.

// A build script reports broken inputs by panicking; `expect` messages state the invariant.
#![allow(clippy::expect_used)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

use sha2::{Digest, Sha256};

struct Entry {
    id: String,
    version: u32,
    prompt: PathBuf,
    sha256: String,
    schema: Option<PathBuf>,
}

fn main() {
    let dir = Path::new(&env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"))
        .join("prompts");
    println!("cargo:rerun-if-changed={}", dir.display());

    let language_path = dir.join("_language.md");
    let language = fs::read_to_string(&language_path).expect("prompts/_language.md exists");
    let language = language.trim();

    let mut names: Vec<String> = fs::read_dir(&dir)
        .expect("prompts/ is readable")
        .map(|e| {
            e.expect("directory entry")
                .file_name()
                .into_string()
                .expect("UTF-8 file name")
        })
        .collect();
    names.sort();

    let mut entries: Vec<Entry> = Vec::new();
    for name in &names {
        println!("cargo:rerun-if-changed={}", dir.join(name).display());
        if name.starts_with('_') || name.ends_with(".schema.json") {
            continue;
        }
        let stem = name
            .strip_suffix(".md")
            .unwrap_or_else(|| panic!("unexpected file in prompts/: {name}"));
        let (id, version) = stem
            .rsplit_once(".v")
            .unwrap_or_else(|| panic!("prompt {name} must be named <id>.v<N>.md"));
        assert!(
            !id.is_empty() && id.bytes().all(|b| b.is_ascii_lowercase() || b == b'_'),
            "prompt id {id:?} must be lowercase ASCII with underscores"
        );
        let version: u32 = version
            .parse()
            .unwrap_or_else(|_| panic!("prompt {name}: version must be an integer"));
        assert!(version >= 1, "prompt {name}: versions start at 1");
        let path = dir.join(name);
        let text = fs::read_to_string(&path).expect("prompt is readable");
        assert!(
            text.contains(language),
            "prompt {name} must contain the language instruction from prompts/_language.md verbatim"
        );
        let schema = dir.join(format!("{stem}.schema.json"));
        let sha256 = hex::encode(Sha256::digest(text.as_bytes()));
        entries.push(Entry {
            id: id.to_owned(),
            version,
            prompt: path,
            sha256,
            schema: schema.exists().then_some(schema),
        });
    }
    for name in &names {
        if let Some(stem) = name.strip_suffix(".schema.json") {
            assert!(
                names.contains(&format!("{stem}.md")),
                "schema {name} has no prompt {stem}.md"
            );
        }
    }

    let mut out = String::from("// @generated by build.rs from prompts/ — do not edit.\n");
    out.push_str("/// Every prompt, sorted by id then version.\n");
    out.push_str("pub static PROMPTS: &[PromptDef] = &[\n");
    for e in &entries {
        let schema = e.schema.as_ref().map_or_else(
            || "None".to_owned(),
            |p| format!("Some(include_str!({:?}))", p.display().to_string()),
        );
        writeln!(
            out,
            "    PromptDef {{ id: {:?}, version: {}, text: include_str!({:?}), sha256: {:?}, schema: {} }},",
            e.id,
            e.version,
            e.prompt.display().to_string(),
            e.sha256,
            schema
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");
    writeln!(
        out,
        "/// The shared language instruction every prompt contains.\npub const LANGUAGE_INSTRUCTION: &str = {language:?};"
    )
    .expect("writing to a String cannot fail");

    let out_path =
        Path::new(&env::var("OUT_DIR").expect("cargo sets OUT_DIR")).join("prompts_generated.rs");
    fs::write(out_path, out).expect("OUT_DIR is writable");
}
