//! Code emission: typify for types, a small template for operations and streams.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use serde_json::{Value, json};
use typify::{TypeSpace, TypeSpaceImpl, TypeSpaceSettings};

use crate::format::format;
use crate::output::GeneratedFile;
use crate::spec::{Api, Location, Operation, Param};
use crate::{Error, Options};

const LINT_ALLOWS: &str = "#![allow(\n    clippy::all,\n    clippy::pedantic,\n    clippy::restriction,\n    missing_docs,\n    unused,\n    rustdoc::all\n)]";

pub(crate) fn emit(api: &Api, options: &Options) -> Result<Vec<GeneratedFile>, Error> {
    let core: syn::Path = syn::parse_str(&options.core_path)
        .map_err(|e| Error::Spec(format!("core path `{}`: {e}", options.core_path)))?;
    let mut space = type_space(api)?;

    let mut ops = Vec::new();
    let mut streams = Vec::new();
    for op in &api.operations {
        if op.stream.is_some() {
            streams.push(stream_fn(op, &core, &mut space)?);
        } else {
            ops.push(operation_fn(op, &core, &mut space)?);
        }
    }

    let header = format!(
        "// @generated by strata-codegen from {}. Do not edit: run api/generate.sh.\n",
        options.source_label
    );
    let cfg = options.rustfmt_config.as_deref();
    let types = format(space.to_stream(), cfg)?;
    let operations = format(
        quote! {
            //! One function per API operation.
            use super::types;
            #(#ops)*
        },
        cfg,
    )?;
    let streams = format(
        quote! {
            //! One constructor per stream operation (WebSocket, D24).
            use super::types;
            #(#streams)*
        },
        cfg,
    )?;
    let module = format!(
        "{header}//! Generated from the OpenAPI contract: types, operations and streams.\n{LINT_ALLOWS}\n\npub mod operations;\npub mod streams;\npub mod types;\n"
    );

    Ok(vec![
        GeneratedFile::new("mod.rs", module),
        GeneratedFile::new("operations.rs", format!("{header}{operations}")),
        GeneratedFile::new("streams.rs", format!("{header}{streams}")),
        GeneratedFile::new(
            "types.rs",
            format!("{header}//! Types of the contract's component schemas.\n{types}"),
        ),
    ])
}

fn type_space(api: &Api) -> Result<TypeSpace, Error> {
    let mut settings = TypeSpaceSettings::default();
    settings
        .with_type_mod("types")
        .with_derive("PartialEq".to_owned())
        .with_replacement("Binary", "::serde_bytes::ByteBuf", std::iter::empty())
        .with_conversion(
            schema_object(&json!({ "type": "string", "format": "ulid" }))?,
            "::ulid::Ulid",
            [TypeSpaceImpl::FromStr, TypeSpaceImpl::Display].into_iter(),
        );
    let mut space = TypeSpace::new(&settings);
    let defs = api
        .schemas
        .iter()
        .map(|(name, schema)| Ok((name.clone(), schema_of(schema)?)))
        .collect::<Result<Vec<_>, Error>>()?;
    space
        .add_ref_types(defs)
        .map_err(|e| Error::Types(e.to_string()))?;
    Ok(space)
}

fn schema_of(value: &Value) -> Result<schemars08::schema::Schema, Error> {
    let mut value = value.clone();
    unsigned_formats(&mut value);
    serde_json::from_value(value.clone()).map_err(|e| Error::Types(format!("schema {value}: {e}")))
}

/// utoipa documents Rust's unsigned integers as `int32`/`int64` with `minimum: 0`; typify only
/// looks at the format, so rewrite them to `uint32`/`uint64` to get `u32`/`u64` back.
fn unsigned_formats(value: &mut Value) {
    match value {
        Value::Object(map) => {
            let non_negative = map
                .get("minimum")
                .and_then(Value::as_f64)
                .is_some_and(|m| m >= 0.0);
            if non_negative && map.get("type").and_then(Value::as_str) == Some("integer") {
                let unsigned = match map.get("format").and_then(Value::as_str) {
                    Some("int32") => Some("uint32"),
                    Some("int64") => Some("uint64"),
                    _ => None,
                };
                if let Some(unsigned) = unsigned {
                    map.insert("format".to_owned(), Value::String(unsigned.to_owned()));
                }
            }
            map.values_mut().for_each(unsigned_formats);
        }
        Value::Array(items) => items.iter_mut().for_each(unsigned_formats),
        _ => {}
    }
}

fn schema_object(value: &Value) -> Result<schemars08::schema::SchemaObject, Error> {
    serde_json::from_value(value.clone()).map_err(|e| Error::Types(format!("schema {value}: {e}")))
}

/// Tokens of the Rust type for `schema`, adding inline schemas to the type space.
fn type_tokens(space: &mut TypeSpace, schema: &Value, hint: String) -> Result<TokenStream, Error> {
    let id = space
        .add_type_with_name(&schema_of(schema)?, Some(hint))
        .map_err(|e| Error::Types(e.to_string()))?;
    let ty = space
        .get_type(&id)
        .map_err(|e| Error::Types(e.to_string()))?;
    Ok(ty.ident())
}

fn pascal(s: &str) -> String {
    s.split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_ascii_uppercase().to_string() + chars.as_str()
            })
        })
        .collect()
}

const RESERVED: [&str; 12] = [
    "client", "body", "options", "request", "as", "type", "match", "move", "ref", "self", "fn",
    "mod",
];

fn snake_ident(name: &str) -> syn::Ident {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 && !out.ends_with('_') {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else if c.is_ascii_alphanumeric() {
            out.push(c);
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    let mut out = out.trim_matches('_').to_owned();
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert_str(0, "p_");
    }
    if RESERVED.contains(&out.as_str()) {
        out.push_str("_param");
    }
    format_ident!("{}", out)
}

fn docs(op: &Operation, kind: &str) -> TokenStream {
    let mut lines = Vec::new();
    if let Some(summary) = &op.summary {
        lines.push(format!(" {summary}"));
    }
    if let Some(description) = &op.description {
        lines.push(String::new());
        lines.extend(description.lines().map(|l| format!(" {l}")));
    }
    if !lines.is_empty() {
        lines.push(String::new());
    }
    lines.push(format!(" `{} {}`{kind}", op.method.to_uppercase(), op.path));
    quote! { #( #[doc = #lines] )* }
}

/// A parameter's argument type and the expression producing its string form.
struct ParamCode {
    ident: syn::Ident,
    ty: TokenStream,
    to_string: TokenStream,
}

fn param_code(
    op: &Operation,
    param: &Param,
    core: &syn::Path,
    space: &mut TypeSpace,
) -> Result<ParamCode, Error> {
    let ident = snake_ident(&param.name);
    let v = quote! { value };
    let schema = &param.schema;
    let ty_name = schema.get("type").and_then(Value::as_str);
    let format = schema.get("format").and_then(Value::as_str);
    let is_ref = schema.get("$ref").is_some() || schema.get("enum").is_some();
    let (ty, to_string) = match (ty_name, format) {
        (Some("string"), Some("ulid")) => (quote! { ::ulid::Ulid }, quote! { #v.to_string() }),
        (Some("string"), _) if !is_ref => (quote! { &str }, quote! { (*#v).to_owned() }),
        (Some("boolean"), _) => (quote! { bool }, quote! { #v.to_string() }),
        (Some("number"), _) => (quote! { f64 }, quote! { #v.to_string() }),
        (Some("integer"), _) => {
            let unsigned = schema
                .get("minimum")
                .and_then(Value::as_f64)
                .is_some_and(|m| m >= 0.0);
            let ty = if unsigned {
                quote! { u64 }
            } else {
                quote! { i64 }
            };
            (ty, quote! { #v.to_string() })
        }
        _ => {
            let hint = format!("{}{}", pascal(&op.id), pascal(&param.name));
            let ty = type_tokens(space, schema, hint)?;
            (quote! { &#ty }, quote! { #core::param_string(#v)? })
        }
    };
    let ty = if param.required {
        ty
    } else {
        quote! { ::std::option::Option<#ty> }
    };
    Ok(ParamCode {
        ident,
        ty,
        to_string,
    })
}

/// `format!` expression for the path with path parameters encoded.
fn path_expr(op: &Operation, codes: &[(&Param, ParamCode)], core: &syn::Path) -> TokenStream {
    let mut template = op.path.replace('{', "{{").replace('}', "}}");
    let mut args = Vec::new();
    for (param, code) in codes.iter().filter(|(p, _)| p.location == Location::Path) {
        template = template.replacen(&format!("{{{{{}}}}}", param.name), "{}", 1);
        let ident = &code.ident;
        let to_string = &code.to_string;
        args.push(quote! {
            #core::encode_path_segment(&{ let value = &#ident; #to_string })?
        });
    }
    if args.is_empty() {
        quote! { ::std::string::String::from(#template) }
    } else {
        quote! { ::std::format!(#template, #(#args),*) }
    }
}

fn operation_fn(
    op: &Operation,
    core: &syn::Path,
    space: &mut TypeSpace,
) -> Result<TokenStream, Error> {
    let name = snake_ident(&op.id);
    let id = &op.id;
    let method = format_ident!("{}", op.method.to_uppercase());
    let codes = op
        .params
        .iter()
        .map(|p| Ok((p, param_code(op, p, core, space)?)))
        .collect::<Result<Vec<_>, Error>>()?;
    let args = codes.iter().map(|(_, c)| {
        let (ident, ty) = (&c.ident, &c.ty);
        quote! { #ident: #ty }
    });
    let path = path_expr(op, &codes, core);

    let mut steps = Vec::new();
    if op.auth {
        steps.push(quote! { let request = request.authenticated(); });
    }
    for (param, code) in codes.iter().filter(|(p, _)| p.location != Location::Path) {
        let (ident, to_string) = (&code.ident, &code.to_string);
        let name = &param.name;
        let add = if param.location == Location::Header {
            quote! { request.header(#name, #to_string) }
        } else {
            quote! { request.query(#name, #to_string) }
        };
        steps.push(if param.required {
            quote! { let request = { let value = &#ident; #add }; }
        } else {
            quote! {
                let request = match &#ident {
                    ::std::option::Option::Some(value) => #add,
                    ::std::option::Option::None => request,
                };
            }
        });
    }

    let body_arg = match &op.body {
        None => None,
        Some((schema, required)) => {
            let ty = type_tokens(space, schema, format!("{}Body", pascal(&op.id)))?;
            if *required {
                steps.push(quote! { let request = request.body(body)?; });
                Some(quote! { body: &#ty })
            } else {
                steps.push(quote! {
                    let request = match body {
                        ::std::option::Option::Some(body) => request.body(body)?,
                        ::std::option::Option::None => request,
                    };
                });
                Some(quote! { body: ::std::option::Option<&#ty> })
            }
        }
    };
    let (ret, send) = match &op.response {
        Some(schema) => (
            type_tokens(space, schema, format!("{}Response", pascal(&op.id)))?,
            quote! { client.send(request).await },
        ),
        None => (quote! { () }, quote! { client.send_empty(request).await }),
    };
    let doc = docs(op, "");
    Ok(quote! {
        #doc
        pub async fn #name(
            client: &#core::Client,
            #(#args,)*
            #body_arg
        ) -> ::std::result::Result<#ret, #core::Error> {
            let request = #core::Request::new(#core::Method::#method, #path, #id);
            #(#steps)*
            #send
        }
    })
}

fn stream_fn(
    op: &Operation,
    core: &syn::Path,
    space: &mut TypeSpace,
) -> Result<TokenStream, Error> {
    let name = snake_ident(&op.id);
    let id = &op.id;
    let payload = op.stream.as_deref().unwrap_or_default();
    let payload_ty = type_tokens(
        space,
        &json!({ "$ref": format!("#/components/schemas/{payload}") }),
        pascal(payload),
    )?;
    let codes = op
        .params
        .iter()
        .map(|p| Ok((p, param_code(op, p, core, space)?)))
        .collect::<Result<Vec<_>, Error>>()?;
    let args = codes.iter().map(|(_, c)| {
        let (ident, ty) = (&c.ident, &c.ty);
        quote! { #ident: #ty }
    });
    let path = path_expr(op, &codes, core);
    let auth = op.auth;
    let doc = docs(op, " (WebSocket stream)");
    Ok(quote! {
        #doc
        pub fn #name(
            client: &#core::Client,
            #(#args,)*
            options: #core::streaming::StreamOptions,
        ) -> ::std::result::Result<#core::streaming::Subscription<#payload_ty>, #core::Error> {
            ::std::result::Result::Ok(#core::streaming::Subscription::new(client, #path, #id, #auth, options))
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_are_sanitised() {
        let cases = [
            ("If-Match", "if_match"),
            ("resume_from", "resume_from"),
            ("getWidget", "get_widget"),
            ("type", "type_param"),
            ("body", "body_param"),
            ("9lives", "p_9lives"),
        ];
        for (input, expected) in cases {
            assert_eq!(snake_ident(input).to_string(), expected);
        }
        assert_eq!(pascal("create_widget"), "CreateWidget");
        assert_eq!(pascal("If-Match"), "IfMatch");
    }
}
